# -*- coding: utf-8 -*-
"""dashboard submission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdWBYdThLrhxcGtEiW7D5uru_nZ5ruKj
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Konfigurasi Halaman Streamlit
st.set_page_config(
    page_title="HR Attrition Analytics Dashboard",
    page_icon="👥",
    layout="wide"
)

# Judul Dashboard
st.title("👥 HR Attrition Prediction Dashboard")
st.markdown("Dashboard ini menampilkan hasil evaluasi pemodelan Machine Learning untuk memprediksi keluarnya karyawan (Attrition).")
st.divider()

# --- DATA PREPARATION ---
# Data Ketidakseimbangan Kelas (Berdasarkan gambar)
class_data = pd.DataFrame({
    'Status': ['Retained (Class 0)', 'Attrition (Class 1)'],
    'Jumlah Karyawan': [173, 39]
})

# Data Performa Model (Berdasarkan gambar dataframe)
model_data = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'XGBoost', 'SVM'],
    'Accuracy': [0.844340, 0.839623, 0.801887, 0.844340],
    'Precision': [0.800000, 0.727273, 0.428571, 1.000000],
    'Recall': [0.205128, 0.205128, 0.230769, 0.153846],
    'F1 Score': [0.326531, 0.320000, 0.300000, 0.266667]
})

# --- ROW 1: KONDISI DATA & SUMMARY METRICS ---
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("Distribusi Kelas (Imbalanced Data)")
    # Visualisasi Pie Chart Matplotlib
    fig1, ax1 = plt.subplots(figsize=(5, 5))
    colors = sns.color_palette("pastel")[0:2]
    ax1.pie(class_data['Jumlah Karyawan'], labels=class_data['Status'], autopct='%1.1f%%',
            colors=colors, startangle=90, explode=(0, 0.1), shadow=True)
    ax1.axis('equal')
    st.pyplot(fig1)
    st.caption("Data sangat tidak seimbang; metrik Akurasi bisa menyesatkan.")

with col2:
    st.subheader("Highlight Performa Model Terbaik")
    st.markdown("""
    Berdasarkan pengujian, **Logistic Regression** terpilih sebagai model paling optimal.
    Meskipun SVM memiliki Precision 100%, dan XGBoost memiliki Recall tertinggi, Logistic Regression menawarkan keseimbangan terbaik (F1-Score).
    """)

    # Menampilkan Metric ala Streamlit
    m1, m2, m3 = st.columns(3)
    best_f1 = model_data['F1 Score'].max()
    best_acc = model_data[model_data['Model'] == 'Logistic Regression']['Accuracy'].values[0]

    m1.metric(label="Model Terbaik", value="Log. Regression")
    m2.metric(label="Top F1-Score (Class 1)", value=f"{best_f1:.4f}")
    m3.metric(label="Top Accuracy", value=f"{best_acc:.2%}")

st.divider()

# --- ROW 2: TABEL & GRAFIK PERBANDINGAN MODEL ---
st.subheader("Perbandingan Performa Model (Fokus pada Kelas Attrition)")

col3, col4 = st.columns([1, 1])

with col3:
    st.markdown("**Tabel Rincian Evaluasi Metrik**")
    # Styling dataframe menggunakan pandas
    st.dataframe(
        model_data.style.highlight_max(subset=['Accuracy', 'Precision', 'Recall', 'F1 Score'],
                                       color='lightgreen', axis=0),
        use_container_width=True
    )

with col4:
    st.markdown("**Visualisasi F1-Score per Model**")
    # Bar plot menggunakan Seaborn
    fig2, ax2 = plt.subplots(figsize=(6, 4))
    sns.barplot(x='F1 Score', y='Model', data=model_data.sort_values('F1 Score', ascending=False),
                palette='viridis', ax=ax2)
    ax2.set_xlabel('F1 Score (Skor Keseimbangan)')
    ax2.set_ylabel('')
    st.pyplot(fig2)

# --- ROW 3: REKOMENDASI SELANJUTNYA ---
st.divider()
st.subheader("Rekomendasi Bisnis & Teknis")
st.info("""
**Langkah Selanjutnya untuk Iterasi Model:**
1. **Penerapan SMOTE:** Lakukan *oversampling* pada kelas minoritas (Attrition) di tahap prapemrosesan agar nilai *Recall* bisa naik dari batas ~0.20 saat ini.
2. **Hyperparameter Tuning:** Eksplorasi bobot kelas (`class_weight='balanced'`) pada Logistic Regression dan Random Forest.
3. **Analisis Fitur (Feature Importance):** Ekstrak bobot koefisien dari Logistic Regression untuk mengetahui faktor utama apa (misal: *OverTime*, *BusinessTravel*) yang paling mendorong karyawan untuk *resign*.
""")