# -*- coding: utf-8 -*-
"""Notebook Submission Penerapan Data Science.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZ_0mFSl1MwkltMqiVyV7Al0auHUMw-U

# Proyek Akhir: Menyelesaikan Permasalahan Perusahaan Edutech

- Nama: Riana Shofiatul Khoeriyah
- Email: rianashofiatulkhoeriyah24@gmail.com
- Id Dicoding: riana_sk

## Persiapan

### Menyiapkan library yang dibutuhkan

Pada bagian ini dipergunakan untuk menginstall dan mengimport seluruh library yang dibutuhkan dalam pengerjaan proyek akhir ini.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import joblib
import math

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from scipy.stats import chi2_contingency
from sklearn.feature_selection import SelectKBest, chi2
from imblearn.over_sampling import SMOTE

from google.colab import drive
drive.mount('/content/drive')

"""##Menyiapkan data yang akan digunakan"""

df = pd.read_csv('/content/drive/MyDrive/proyek_pertama_penerapan_data_science/employee_data.csv')
df.head()

"""## Data Understanding"""

df.info()

"""Data dalam file employee_data.csv ini berisi rincian demografi atau metrik yang berkaitan dengan pekerjaan dan status pengunduran diri (attrition).
  - EmployeeId - ID unik setiap karyawan      
  - Age - Umur karyawan (tahun)     
  - Attrition - Status pengunduran diri karyawan (Yes = Keluar, No = Tetap bekerja)                 
  - BusinessTravel - Frekuensi perjalanan dinas (Non-Travel, Travel_Rarely, Travel_Frequently)       
  - DailyRate - Pendapatan atau tarif harian karyawan          
  - Department - Departemen tempat karyawan bekerja (Sales, RnD, Human Resources)      
  - DistanceFromHome - Jarak rumah ke tempat kerja         
  - Education - Tingkat pendidikan karyawan (SMA, S1, S2, dan lainnya)                 
  - EducationField - Pidang pendidikan (Science, Economy, Psycology, Engineering, dll)
  - EmployeeCount - Jumlah karyawan
  - EnvironmentSatisfaction - Tingkat kepuasan terhadap lingkungan kerja
  - Gender - Jenis kelamin karyawan     
  - HourlyRate - Pendapatan atau tarif per jam          
  - JobInvolvement - Tingkat keterlibatan dalam pekerjaan       
  - JobLevel - Tingkat jabatan karyawan          
  - JobRole - Posisi atau jabatan                  
  - JobSatisfaction - Tingkat kepuasan terhadap pekerjaan
  - MaritalStatus - Status pernikahan (Single, Married, Divorced)
  - MonthlyIncome - Pendapatan bulanan            
  - MonthlyRate - Tarif atau nilai bulanan (Bukan gaji bulanan)        
  - NumCompaniesWorked - Jumlah perusahaan tempat karyawan pernah bekerja sebelumnya.
  - Over18 - Apakah karyawan berusia diatas 18 tahun.                
  - OverTime - Apakah karyawan sering lembur              
  - PercentSalaryHike - Persentase kenaikan gaji terakhir       
  - PerformanceRating - Nilai performa karyawan      
  - RelationshipSatisfaction - Tingkat kepuasan hubungan kerja dengan atasan atay rekan kerja
  - StandardHours - Jam kerja standar
  - StockOptionLevel - tingkat kepemilikan saham perusahaan
  - TotalWorkingYears - Total pengalaman kerja
  - TrainingTimesLastYear - Jumlah pelatihan yang diikuti selama 1 tahun terakhir
  - WorkLifeBalance - Tingkat keseimbangan kerja dan kehidupan pribadi
  - YearsAtCompany - Lama bekerja di perusahaan saat ini (tahun)
  - YearsInCurrentRole - Lama berada pada posisi/jabatan saat ini
  - YearsSinceLastPromotion - Lama sejak promosi terakhir (tahun)
  - YearsWithCurrManager - Lama bekerja dengan manager saat ini (tahun)

##Cek Nilai Unik untuk Setiap Variabel Kategorik
"""

for feature in df.select_dtypes(include='object'):
  print(feature)
  print(df[feature].unique(), '\n')

"""##Melihat Statistik Deskriptif untuk seluruh variabel"""

df.describe()

df.describe(include='object')

"""Berdasarkan analisis statistik deskriptif yang telah dilakukan, semua karyawan berusia di atas 18 tahun, hal ini dilihat dari fitur `Over18` yang memiliki 1 data, yaitu Y. Selain itu, fitur `EmployeeCount` juga memiliki 1 nilai unik. Oleh karena itu, kita dapat mengeliminasi kedua fitur ini karena tidak memiliki pengaruh besar terhadap masalah bisnis."""

df = df.drop(['Over18', 'EmployeeCount'], axis=1, errors='ignore')
df.head()

"""## Data Preparation / Preprocessing

##Penanganan Missing Value dan Duplikat
"""

df.isnull().sum()

"""Dalam penanganan missing value dan duplikat ini, dataset memiliki beberapa nilai yang hilang dalam fitur `Attrition`. Fitur `Attrition` ini merupakan fitur utama dalam masalah bisnis yang akan diselesaikan, kita perlu menghapus data dengan nilai yang hilang tersebut."""

df.dropna(inplace=True)
df.isnull().sum()

"""Selanjutnya kita lakukan pengecekan duplikasi data"""

df.duplicated().sum()

"""Hasilnya, tidak ada data yang duplikat

##Exploratory Data Analysis (EDA)

##Decoding Variabel Kategorik

Decoding Ordinal untuk fitur-fitur berikut:
- Education
  - 1: Below College
  - 2: College
  - 3: Bachelor
  - 4: Master
  - 5: Doctor
- EnvironmentSatisfaction
  - 1: Low
  - 2: Medium
  - 3: High
  - 4: Very High
- JobInvolvement
  - 1: Low
  - 2: Medium
  - 3: High
  - 4: Very High
- JobSatisfaction
  - 1: Low
  - 2: Medium
  - 3: High
  - 4: Very High
- PerformanceRating
  - 1: Low
  - 2: Good
  - 3: Excellent
  - 4: Outstanding
- RelationshipSatisfaction
  - 1: Low
  - 2: Medium
  - 3: High
  - 4: Very High
- WorkLifeBalance
  - 1: Low
  - 2: Good
  - 3: Excellent
  - 4: Outstanding
"""

def ordinal_decoding(df, features_to_decode):
    """
    Convert encoded feature(s) in a DataFrame to corresponding categorical labels

    Parameters
        df (pandas.DataFrame) : The DataFrame with feature(s) to be converted
        features_to_decode (str or list of str) : The feature name(s) to convert

    Returns
        pandas.DataFrame : The DataFrame with feature(s) as categorical labels
    """
    # Ensure features_to_decode is always a list for consistent iteration
    if isinstance(features_to_decode, str):
        features_to_decode = [features_to_decode]

    for feature_name in features_to_decode:
        category_map = {} # Initialize for each feature_name to prevent UnboundLocalError

        if feature_name == 'Attrition':
            category_map = {0: 'No', 1: 'Yes'}
        elif feature_name == 'Education':
            category_map = {1: 'Below College', 2: 'College', 3:'Bachelor', 4:'Master', 5:'Doctor'}
        elif feature_name in ['WorkLifeBalance', 'PerformanceRating']:
            category_map = {1: 'Low', 2: 'Good', 3:'Excellent', 4:'Outstanding'}
        elif feature_name in ['EnvironmentSatisfaction', 'JobInvolvement', 'JobSatisfaction', 'RelationshipSatisfaction']:
            category_map = {1: 'Low', 2: 'Medium', 3:'High', 4:'Very High'}

        if category_map: # Only apply mapping if a category_map was found for the feature_name
            df[feature_name] = df[feature_name].map(category_map)
        else:
            print(f"Warning: No specific ordinal mapping defined for feature '{feature_name}'. Skipping decoding for this feature.")

    return df

df = ordinal_decoding(df, 'Attrition')
df = ordinal_decoding(df, 'Education')
df = ordinal_decoding(df, ['EnvironmentSatisfaction', 'JobInvolvement', 'JobSatisfaction', 'RelationshipSatisfaction'])
df = ordinal_decoding(df, ['PerformanceRating', 'WorkLifeBalance'])

df.head()

"""Melihat statistik deskriptif untuk semua variabel"""

df.describe(include='all')

"""##Analisis Distribusi Kelas Target"""

# Distribusi variabel target (Attrition)
attrition_counts = df['Attrition'].value_counts()
attrition_counts

attrition_percentage = df['Attrition'].value_counts(normalize=True) * 100
attrition_percentage

"""#Distribusi Target (Attrition)

Pada analisis distribusi kelas target attrition, dimana pada kelas target ini memberikan informasi terkait status pengunduran diri karyawan, di dapat beberapa insight sebagai berikut:
- No (Karyawan tetap bekerja): 83.08%
- Yes (Keluar): 16.91%
Hasil dari analisis ini menunjukkan bahwa sebanyak 83.08% atau setara dengan 879 karyawan tetap bekerja, sedangkan `Attrition` tetap signifikan pada angka 16.91% atau setara dengan 179 karyawan yang keluar.

##Analisis Fitur Numerik
"""

numerical, categorical = [], []

for feature in df.columns:
  if not df[feature].dtype == 'object':
    numerical.append(feature)
  else:
    categorical.append(feature)

numerical_description = df[numerical].describe()
numerical_description

"""#Deskripsi Kolom Numerik

- `Age`: Rata-rata karyawan berusia 37 tahun.
- `MonthlyIncome`: Rata-rata pendapatan karyawan sebanyak 6,6 juta.
- DistanceFromHome: Sebagian besar karyawan tinggal dekat dengan kantor yang berjarak rata-rata 8,9 km.
- YearsAtCompany: Sebagian besar karyawan bekerja di perusahaan selama 5 - 9 tahun.
"""

df[numerical].hist(bins=15, figsize=(10, 10))
plt.tight_layout()
plt.show()

"""Berdasarkan grafik histogram diatas, sebagian besar fitur numerik menunjukkan distribusi yang condong ke arah kanan (right-skewed). Fitur-fitur yang termasuk ke dalam right-skewed diantaranya `DistanceFromHome`, `MonthlyIncome`, `NumCompaniesWorked`, `PercentSalaryHike`, `TotalWorkingYears`, `YearsAtCompany`, `YearsInCurrentRole`, `YearsSinceLastPromotion`, `JobLevel`, `StockOptionLevel`, dan `YearsWithCurrManager`. Hal ini mengindikasikan bahwa sebagian besar nilai berada pada kisaran rendah, sementara hanya sedikit yang memiliki nilai tinggi. Sementara itu, fitur `Age` dan `TrainingTimesLastYear` memiliki distribusi yang lebih simetris atau mendekatii normal, mencerminkansebaran nilai yang relatif seimbang di rat-rata. Kemudian, beberapa fitur lain seperti `EmployeeId`, `DailyRate`, `HourlyRate`, dan `MonthlyRate` memiliki sebaran yang merata tanpa pola distribusi khusus. Selain itu, terdapat fitur seperti `EmployeeCount` dan `StandartHours` tidak memiliki variasi sebaran sama sekali, sehinggga kemungkinan tidak memiliki kontribusi informasi dalam proses pemodelan selanjutnya.

##Analisis Hubungan Fitur Numerik terhadap Target

Dengan menggunakan visualisasi, kita dapat meihat hubungan fitur numerik terhadap `Attrition`
"""

plt.figure(figsize=(10, 8))
sns.boxplot(data=df, x='Attrition', y='Age', palette='Set3')
plt.title('Age Distribution by Attrition')
plt.show()

plt.figure(figsize=(10, 8))
sns.boxplot(data=df, x='Attrition', y='MonthlyIncome', palette='Set3')
plt.title('Monthly Income Distribution by Attrition')
plt.show()

plt.figure(figsize=(10, 8))
sns.boxplot(data=df, x='Attrition', y='DistanceFromHome', palette='Set3')
plt.title('Distance From Home Distribution by Attrition')
plt.show()

"""##Hasil Analisis Fitur Numerik
- `Age`: Karyawan dengan `Attrition` pada rentang umur 30 - 45 tahun cenderung lebih memilih tetap bekerja, dibandingkan dengan karyawan dengan rentang usia 25 - 38 tahun.
- `MonthlyIncome`: Karyawan dengan `Attrition` memiliki distribusi pendaptan yang lebih rendah dibandingkan dengan karyawan yang memilih tetap bekerja.
- `DistanceFromHome`: Tidak ada perbedaan yang signifikan dalam jarak kantor dari rumah karyawan yang keluar dengan yang tetap bekerja.

##Distribusi YearsAtCompany dan TotalWorkingYears

Menganalisis distribusi fitur `YearsAtCompany` dan `TotalWorkingYear` karena fitur ini relevan dalam memengaruhi `Attrition`.
"""

plt.figure(figsize=(10, 8))
sns.histplot(data=df, x='YearsAtCompany', hue='Attrition', kde=True, palette='Set3', bins=30)
plt.title('Years At Company Distribution by Attrition')
plt.xlabel('Years At Company')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 8))
sns.histplot(data=df, x='TotalWorkingYears', hue='Attrition', kde=True, palette='Set3', bins=30)
plt.title('Total Working Years Distribution by Attrition')
plt.xlabel('Total Working Years')
plt.ylabel('Count')
plt.show()

"""Berdasarkan distribusi fitur `YearsAtCompany` dan `TotalWorkingYears` terhadap `Attrition`:
1. `YearsAtCompany`
  -  Karyawan dengan masa kerja singkat yakni sekitar 0 - 5 tahun masa kerja, memiliki risiko `Attrition` lebih tinggi.
  - Distribusi menunjukkan bahwa karyawan baru memiliki kecenderungan untuk lebih cepat.
2. `TotalWorkingYears`
  - Karyawan dengan pengalaman kerja kebih sedikit yakni sekitar 0 - 10 tahun kebih sering keluar dibandingkan yang memiliki pengalaman kerj alebih panjang.
  - Hal ini menunjukkan pentingknya retensi awal karir dan pengalaman karyawan.

##Analisis Interaksi Antar Fitur

Bagian ini digunakan untuk melihat hubungan antara dua fitur utama dan bagaimana keduanya berinteraksi dengan target `Attrition`.
"""

plt. figure(figsize=(10, 8))
sns.scatterplot(data=df, x='MonthlyIncome', y='Age', hue='Attrition', style='OverTime', palette='Set1')
plt.title('Interaction Between Monthly Income, Age, and OverTime to Attrition')
plt.xlabel('Monthly Income')
plt.ylabel('Age')
plt.legend(title='Attrition and OverTime')
plt.show()

"""Grafik di atas menunjukkan hubungna antar fitur `MonthlyIncome`, `Age`, dan `Overtime` dengan `Attrition`.
1. `Attrition` dan `Overtime`
  - Karyawan yang sering lembur yang ditandai dengan * cenderung lebih sering mengalami attrition yang ditandai dengan warna merah dibandingkan dengan yang tidak lembur.
2. `Attrition` dan `MonthlyIncome`
  - Karyawan dengan pendapatan bulanan yang lebih rendah memiliki tingkat attrition lebih tinggi dibandingkan dengan karyawan yang berpendaptan lebih tinggi.
  - Hal ini terlihat dari kepadatan titik merah yang lebih banyak di sisi koro grafik (pendapatan bulanan rendah).
3. `Attrition` dan `Age`
  - Karyawan yang lebih muda cenderung mengalami attrition lebih sering, terlihat daru konsentrasi titik biru di bagian bawah grafik (usia rendah).
4. Interaksi antara Ketiga Variabel
  - Karyawan yang muda, berpendapatan rendah, dan sering lembur memiliki kecenderungan attrition yang lebih tinggi.

##Hubungan Fitur Kategorik terhadap Target
"""

for feature in categorical:
  contingency_table = pd.crosstab(df[feature], df['Attrition'])
  contingency_table.div(contingency_table.sum(1), axis=0).plot(kind='bar', stacked=True, figsize=(10, 6))
  plt.title(f'Distribution of Attrition by {feature}')
  plt.ylabel('Proportion')
  plt.xlabel(feature)
  plt.legend(title='Attrition')
  plt.xticks(rotation=45, ha='right')
  plt.tight_layout()
  plt.show()

"""Dari stacked bar chart diatas, beberapa insight yang diperoleh diantaranya:
1. `OverTime`: Karyawan yang sering lembur (OverTime = Yes) memiliki proporsi attrition yang jauh lebih tinggi.
2. `MaritalStatus`: Karyawan dengan status single lebih tentang keluar dibandingkan dengan karyawan yang sudah menikah atau bercerai.
3. `JobRole`: berapa peran seperti Sales Representative dan Laboratory Technician, memiliki attrition yang tinggi.
4. `BusinessTravel`: Karyawan yang sering melakukan peerjalanan bisnis memiliki risiko keluar lebih tinggi dibandingkan kategori lainnya.

##Menggunakan Chi-Square Test
"""

categorical = [feature for feature in categorical if feature != 'Attrition']

chi_square_results = []

for feature in categorical:
    contingency_table = pd.crosstab(df[feature], df['Attrition'])
    chi2, p, dof, expected = chi2_contingency(contingency_table)
    chi_square_results.append({
        'Feature': feature,
        'Chi-Square Statistic': chi2,
        'p-value': p})

chi_square_results_df = pd.DataFrame(chi_square_results)
chi_square_results_df

"""##Hasil Chi-Square Test

1. Fitur Signifikan terhadap Attrition (p-value < 0.05):
  - `BusinessTravel`: Karyawan dengan frekuensi perjalanan bisnis tertentu lebih cenderung mengalami attrition.
  - `JobInvolvement`: Karyawan yang terlibat lebih dalam pekerjaan mereka menunjukkan kecenderungan lebih tinggi yntuk mengalami attition.
  - `JobRole`:  Peran pekerjaan tertentu meemiliki hubungan yang sangat signifikan dengan risiko keluar karyawan.
  - `MaritalStatus`: Status pernikahan akan mempengaruhi kecenderungan karyawan untuk keluar, terutama bagi mereka yang berstatus single.
  - `OverTime`: Karyawan yang sering lembur sangat cenderung mengalami attrition.
  - `WorkLifeBalance`: Karyawan yang merasa tidak seimbang antara beban pekerjaan dan kehidupan pribadi memiliki kecenderungan yang lebih tinggi untuk keluar.
2. Fitur Tidak Signifikan (p-value >+ 0.05):
  - `Department`: Tidak ada hubungan antara departemen dan attrition.
  - `Education`:Tingkat pendidikan tidak mempengaruhi attrition secara signifikan.
  - `Gender`: Jenis kelamin tidak memiliki pengaruh terhadap kecenderungan attrition karyawan.
  - `PerformanceRating`: Penilaian kinerja tidak memiliki hubungan signifikan dengan attrition.
  - `RelationshipSatisfaction`: Kepuasan hubungan kerja tidak memiliki pengaruh yang signifikan terhadap attrition.

##Kolerasi Antar Variabel

###Kolerasi Variabel Numerik
"""

correlation_matrix= df[numerical].corr()
correlation_matrix

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix')
plt.show()

"""Fitur-fitur yang sudah divisualisasikan menggunakan heatmap. Diperoleh insight bahwa fitur-fitur seperti `MonthlyIncome`, `TotalYearsWorking`, dan `YearsAtCompany` memiliki korelasi positif yang kuat (0.77)

##Korelasi Variabel Kategorik
"""

# Cramer's V for Categorical-Categorical Correlation
def cramers_v(confusion_matrix):
  chi2 = chi2_contingency(confusion_matrix)[0]
  n = confusion_matrix.sum()
  return np.sqrt(chi2 / (n*(min(confusion_matrix.shape)-1)))

cramers_v_results = []
for i, feature1 in enumerate(categorical):
  for feature2 in categorical[i+1:]:
    confusion_matrix = pd.crosstab(df[feature1], df[feature2])
    cramers_v_value = cramers_v(confusion_matrix)
    cramers_v_results.append({
        'Feature1': feature1,
        'Feature2': feature2,
        'Cramers V': cramers_v_value})

cramers_v_results_df = pd.DataFrame(cramers_v_results)
cramers_v_results_df

"""##Hasil Cramer's V (Hubungan Variabel Kategorikal)

1. Hubungan Tinggi (Cramer's V > 0.3):
- `BusinessTravel` dan `JobRole`: Ada hubungan moderat antara frekuensi perjalanan bisnis dengan jenis pekerjaan.
- `Gender` dan `JobRole`: Ada hubungan moderat antara gender dan jenis pekerjaan.
2. Hubungan Rendah (Cramer's C < 0.3):
- Sebagian besar hubungan antar variabel kategorikal bersifat lemah, seperti hubungan antara `BusinessTravel` dan `MaritalStatus`.

## Data Preprocessing

Karena ada beberapa fitur yang tidak berkontribusi atau memengaruhi tingkat pengunduran diri dalam dataset ini, seperti EmployeeID, fitur-fitur ini perlu di hapus.
"""

df = df.drop(['EmployeeId'], axis=1)

"""## Label Encoding

Pada bagian ini akan dilakukan:
- Memisahkan fitur numerik dan kategorikal dalam dataset.
- Mengubah fitur kategorikal agar dapat menjadi format numerik menggunakan Label Encoding agar bisa digunakan dalam Machine Learning.
"""

numerical, categorical = [], []

for feature in df.columns:
  if not df[feature].dtype == 'object':
    numerical.append(feature)
  else:
    categorical.append(feature)

le = LabelEncoder()
df[categorical] = df[categorical].apply(le.fit_transform)

"""##Data Normalization

Bagian berikut digunakan untuk melakukan normalisasi atau penskalaan pada fitur numerik dalam dataset menggunakan teknik Min-Max Scaling. Penskalaan ini penting untuk memastikan bahwa fitur numerik memiliki skala yang seragam.
"""

scaler = MinMaxScaler()
df[numerical] = scaler.fit_transform(df[numerical])

df

"""Melakukan feature selection dengan RFE"""

x = df.drop('Attrition', axis=1)
y = df['Attrition']

from sklearn.feature_selection import RFE
rfe_selector = RFE(estimator=LogisticRegression(), n_features_to_select=10, step=1)
rfe_selector.fit(x, y)

# Select top features
selected_features = x.columns[rfe_selector.support_]

# Create a new DataFrame with only the selected features
X_selected = df[selected_features]

"""Split Data"""

# Split the data into train and test data
X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

"""Melakukan SMOTE untuk menangani imbalance data"""

# Apply SMOTE to the training data
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

"""## Modeling

Tahapan ini akan dilakukan pemodelan menggunakan berbagai classifier

##Logistic Regression
"""

logistic_model = LogisticRegression(random_state=42, max_iter=1000)
logistic_model.fit(X_train, y_train)
logistic_y_pred = logistic_model.predict(X_test)

"""##Random Forest"""

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
rf_y_pred = rf_model.predict(X_test)

"""##XGBoost Classifier"""

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)
xgb_y_pred = xgb_model.predict(X_test)

"""##SVM"""

svm_model = SVC(random_state=42)
svm_model.fit(X_train, y_train)
svm_y_pred = svm_model.predict(X_test)

"""## Evaluation"""

# Metrics for Logistic Regression
logistic_accuracy = accuracy_score(y_test, logistic_y_pred)
logistic_precision = precision_score(y_test, logistic_y_pred)
logistic_recall = recall_score(y_test, logistic_y_pred)
logistic_f1 = f1_score(y_test, logistic_y_pred)

# Metric for Random Forest
rf_accuracy = accuracy_score(y_test, rf_y_pred)
rf_precision = precision_score(y_test, rf_y_pred)
rf_recall = recall_score(y_test, rf_y_pred)
rf_f1 = f1_score(y_test, rf_y_pred)

# Metric for XGBoost
xgb_accuracy = accuracy_score(y_test, xgb_y_pred)
xgb_precision = precision_score(y_test, xgb_y_pred)
xgb_recall = recall_score(y_test, xgb_y_pred)
xgb_f1 = f1_score(y_test, xgb_y_pred)

# Metric for SVM
svm_accuracy = accuracy_score(y_test, svm_y_pred)
svm_precision = precision_score(y_test, svm_y_pred)
svm_recall = recall_score(y_test, svm_y_pred)
svm_f1 = f1_score(y_test, svm_y_pred)

model_comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest', 'XGBoost', 'SVM'],
    'Accuracy': [logistic_accuracy, rf_accuracy, xgb_accuracy, svm_accuracy],
    'Precision': [logistic_precision, rf_precision, xgb_precision, svm_precision],
    'Recall': [logistic_recall, rf_recall, xgb_recall, svm_recall],
    'F1 Score': [logistic_f1, rf_f1, xgb_f1, svm_f1]
})

model_comparison

# Detailed Clasification Reports
print("Logistic Regression Classification Report:")
print(classification_report(y_test, logistic_y_pred))

print("\nRandom Forest Classification Report:")
print(classification_report(y_test, rf_y_pred))

print("\nXGBoost Classification Report:")
print(classification_report(y_test, xgb_y_pred))

print("\nSVM Classification Report:")
print(classification_report(y_test, svm_y_pred))

"""Hasil dari pemodelan tersebut, menunjukkan bahwa model Logistic Regression sebagai model terbaik.

#Analisis Future Importance Macine Learning
"""

# SHAP values untuk model Random Forest
explainer = shap.TreeExplainer(rf_model)
shap_values = explainer.shap_values(X_test)

# Mengambil feature importance dari model Random Forest
feature_importance = pd.DataFrame({'Feature': X_train.columns, 'Importance': rf_model.feature_importances_})

# Membuat DataFrame untuk feature importance
importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': rf_model.feature_importances_})

# Mengurutkan DataFrame berdasarkan importance
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# Visualisasi Feature Importance
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=importance_df)
plt.title('Feature Importance')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.show()

"""Dari analisisi feature importance tersebut, terlihat bahwa 5 variabel yang paling berpengaruh adalah ...

#Conclusion

Proyek ini bertujuan untuk memahami faktor-faktor yang mempengaruhi tingkat attrition (keluar) karyawan dari perusahaan Jaya Jaya Maju dan membangun model prediktif untuk mengidentifikasi karyawan dengan risiko keluar tinggi. Berikut ini adalah temuan-temuan utama dan insight yang diperoleh:

#1. Faktor-faktor Penyebab Attrition
Berdasarkan analisis data dan model prediktif, berikut adalah faktor utama yang mempengaruhi attrition:
1. `OverTime`
- Karyawan yang sering lembur (OverTime = Yes) memiliki risiko keluar yang jauh lebih tinggi dibandingkan dengan yang tidak lembur.
- Fitur ini adalah prediktor terkuat dalam model prediktif.
2. `MonthlyIncome`
- Pendapatan yang lebih rendah meningkatkan risiko keluar karyawan.
- Fitur ini mencerminkan pentingnya kepuasan finansial dalam retensi karyawan.
3. `YearsAtCompany` dan `TotalWorkingYears`
- Masa kerja pendek baik di perusahaan maupun secara total adalah indikator risiko tinggi.
4. Fitur pendukung lain
- Fitur seperti `DistanceFromHome` dan `Age` memiliki kontribusi kecil, tetapi tetap relevan dalam memahami pola attrition.

#2. Model Prediktif Terbaik
Model terbaik yang digunakan dalam proyek ini adalah Random Forest dengan metrik performa sebagai berikut:
- Accuracy: 84%
- Precision: 85%
- Recall: 99%
- F1-Score: 91%
  
#3. Feature Importance
Dari analisis feature importance menggunakan model Random Forest, didaparkan bahwa:
- `TotalWorkingYears` adalah fitur dengan kontribusi terbesar terhadap prediksi.
- `YearsAtCompany` dan `Age` juga memiliki peran penting.

##Jawaban terhadap Pertanyaan Bisnis
1. Apa faktor utama yang memengaruhi attrition?
- Faktor utama adalah OverTime, MonthlyIncome, dan YearsAtCompany.
2. Bagaimana tingkat kepuasan karyawan memengaruhi attrition?
- Fitur seperti JobSatisfaction tidak signifikan dalam model prediktif, tetapi tetap relevan secara deskriptif.
3. Apa pola perilaku karyawan dengan risiko keluar tinggi?
- Karyawan yang lembur berlebihan, memiliki pendapatan rendah, dan masa kerja pendek cenderung memiliki risiko tinggi.
4. Apakah kita memiliki alat bantu untuk memantau attrition?
- Model prediktif dan visualisasi hasil dapat digunakan untuk membangun dashboard interaktif untuk monitoring risiko.

## Karakteristik Umum Karyawan yang Melakukan Attrition
Berdasarkan analisis data, berikut adalah karakteristik umum karyawan yang melakukan attrition:

1. Demografis:
- Usia: Rata-rata usia karyawan yang keluar adalah 30-an tahun.
- Jenis Kelamin: Mayoritas adalah pria (Male).
- Status Pernikahan: Sebagian besar karyawan yang keluar adalah Single, diikuti oleh Married.
2. Pekerjaan dan Departemen:
- Peran Kerja: Posisi yang paling sering melakukan attrition adalah Laboratory Technician.
- Departemen: Departemen Research & Development memiliki tingkat attrition tertinggi.
3. Faktor Finansial dan Beban Kerja:
- Pendapatan: Rata-rata pendapatan bulanan karyawan yang keluar adalah 4,872.
- Lembur (OverTime): Sebagian besar karyawan yang keluar bekerja lembur secara signifikan.
4. Kepuasan dan Keseimbangan:
- Kepuasan Kerja: Rata-rata tingkat kepuasan kerja adalah 2.5 (Medium).
- Keseimbangan Kerja-Hidup: Rata-rata berada di tingkat 2.67 (Moderate).
5. Masa Kerja:
- Masa Kerja di Perusahaan: Rata-rata masa kerja adalah 5 tahun, dengan beberapa karyawan memiliki masa kerja sangat panjang hingga 40 tahun.

#Rekomendasi Action Items untuk Perusahaan
1. Kurangi Lembur Berlebihan:
Berikan program kerja fleksibel untuk meningkatkan keseimbangan kerja-hidup.
2. Kaji Skala Gaji:
Sesuaikan gaji karyawan agar kompetitif di pasar dan berikan insentif tambahan.
3. Perkuat Retensi Karyawan Baru:
Implementasikan program onboarding dan mentoring untuk karyawan dengan masa kerja pendek.
4. Mengidentifikasi karyawan dengan YearsAtCompany dan TotalWorkingYears yang pendek, lalu memberikan perhatian khusus terhadap pengembangan karier dan kepuasan mereka.
5. Menciptakan lingkungan kerja yang lebih inklusif dan mendukung bagi karyawan dari berbagai kelompok usia.
6. Gunakan Model Prediktif:
Integrasikan model Random Forest untuk memonitor risiko secara real-time melalui dashboard HR.

#Model Export
"""

from google.colab import drive
drive.mount('/content/drive')

joblib.dump(logistic_model, '/content/drive/MyDrive/logistic_model.joblib')
joblib.dump(rf_model, '/content/drive/MyDrive/rf_model.joblib')
joblib.dump(xgb_model, '/content/drive/MyDrive/xgb_model.joblib')
joblib.dump(svm_model, '/content/drive/MyDrive/svm_model.joblib')